// Playable mobile suits: what the select screen shows (Reborn's spec sheet, loadout, a few moves) and the class that
// pilots each one. Every player picks from this list, host and co-op guests alike, and two players may fly the same
// suit. Entries marked `coop` are only offered to guests. To add a suit: a Hero subclass (see gundam.js) and an entry
// here (`cfg` is the suit's config, which the dev tools read its model and moves from); co-op picks it up from the id.
import { Gundam, GUNDAM } from './gundam.js';
import { Guncannon, GUNCANNON } from './guncannon.js';
import { Ball, BALL } from './ball.js';
import { DeltaPlus, DELTAPLUS } from './deltaplus.js';
import { F91, F91_SUIT } from './f91.js';
import { X1Kai, X1KAI } from './x1kai.js';
import { Sazabi, SAZABI } from './sazabi.js';
import { Tank } from './tank.js';

export const ROSTER = [
  {
    id: 'gundam', cls: Gundam, cfg: GUNDAM, pilot: 'amuro',
    unit: 'RX-78-2 GUNDAM', unitShort: 'GUNDAM', unitJp: 'ガンダム', pilotName: 'AMURO RAY', pilotJp: 'アムロ・レイ',
    stats: { MELEE: 600, SHOT: 600, DEFENSE: 485, ARMOR: 10000, MOBILITY: 800, THRUSTER: 1000 },
    equipment: ['Beam Saber ×2', 'Beam Rifle', 'Beam Javelin', 'Hyper Bazooka', 'Shield', 'Gundam Hammer'],
    role: 'All-rounder. Long beam saber reach, a rifle for range, and a weapon for every charge attack.',
    moves: [
      ['J ×6', 'Beam saber string, ending in a launching spin', 'reborn'],
      ['K', 'Beam rifle: mash it, or hold for a charge shot', 'reborn'],
      ['J K (K)', 'Launcher, the beam javelin thrust up · K: shield bash', 'reborn'],
      ['J J K', 'Hyper bazooka, five rounds', 'reborn'],
      ['J×5 K', 'Last Shooting: rifle fired skyward, shockwave', 'reborn'],
      ['SP (hold)', 'Gundam hammer, longer per stock held', 'reborn'],
    ],
    // in-game combo guide: [inputs, what it does, move it starts, source]. J attack, K charge, B boost, U jump, S SP.
    // source: 'reborn' (in Reborn's move footage), 'dwg' (DWG1-3 move lists only) or 'new' (made up here); an array
    // for a row that mixes them, in the text's order. The select screen's `moves` take the same as a third field.
    guide: [
      ['J J J J J J', 'Saber string, launching spin', 'N', 'reborn'],
      ['K', 'Beam rifle · mash, or hold for charge shot', 'C1', 'reborn'],
      ['J K', 'Launcher, javelin thrust up · K: shield bash', 'C2', 'reborn'],
      ['J J K', 'Hyper bazooka, five rounds', 'C3', 'reborn'],
      ['J J J K', 'Twin sabers, then dash through', 'C4', 'reborn'],
      ['J J J J K', 'Rising crescent', 'C5', 'reborn'],
      ['J J J J J K', 'Last Shooting: rifle skyward, shockwave', 'C6', 'reborn'],
      ['B J', 'Dash rush · keep pressing J', 'DA', 'reborn'],
      ['B K', 'Dash cuts, point-blank bazooka', 'DC', 'reborn'],
      ['U J', 'Air slash', 'JA', 'new'],
      ['U K', 'Plunging stab', 'JC', 'new'],
      ['S', 'Javelin storm and slam · hold: hammer', 'SP', 'reborn'],
      ['U S', 'Bazooka barrage', 'SPA', 'reborn'],
    ],
  },
  {
    id: 'guncannon', cls: Guncannon, cfg: GUNCANNON, pilot: 'kai',
    unit: 'RX-77-2 GUNCANNON', unitShort: 'GUNCANNON', unitJp: 'ガンキャノン', pilotName: 'KAI SHIDEN', pilotJp: 'カイ・シデン',
    stats: { MELEE: 600, SHOT: 600, DEFENSE: 567, ARMOR: 8429, MOBILITY: 667, THRUSTER: 790 },
    equipment: ['Beam Rifle', '240mm Cannons'],
    role: 'Artillery brawler. Fists, feet and a giant swing up close, twin shoulder cannons that level anything in front of it.',
    moves: [
      ['J ×6', 'Rifle bash, right hook, straight, two kicks and a launching spin', 'reborn'],
      ['K', 'Beam rifle: mash it, or hold for a twin-cannon salvo', 'reborn'],
      ['J J K', 'Body slam; K again to shell what it bounces up', 'reborn'],
      ['J J J K', 'Three point-blank cannon salvos', 'reborn'],
      ['J×5 K', 'Giant swing: tap K to spin longer', 'reborn'],
      ['SP (hold)', 'Shells in every direction, longer per stock held', 'reborn'],
    ],
    guide: [
      ['J J J J J J', 'Rifle bash, hook, straight, kicks, launching spin', 'N', 'reborn'],
      ['K', 'Beam rifle · mash, or hold for cannon salvo', 'C1', 'reborn'],
      ['J K', 'Flying knee · breaks guard', 'C2', 'reborn'],
      ['J J K', 'Body slam · K again: cannons', 'C3', 'reborn'],
      ['J J J K', 'Point-blank cannon salvos ×3', 'C4', 'reborn'],
      ['J J J J K', 'Juggling shell string', 'C5', 'reborn'],
      ['J J J J J K', 'Giant swing · tap K to spin longer', 'C6', 'reborn'],
      ['B J J J', 'Flying kick, air punch, heel drop', 'DA', 'reborn'],
      ['B K', 'Launch and anti-air blast', 'DC', 'reborn'],
      ['U J', 'Air punch', 'JA', 'new'],
      ['U K', 'Cannons at the ground', 'JC', 'new'],
      ['S', 'Punch storm · hold: shells all around', 'SP', 'reborn'],
      ['U S', 'Hover and shell', 'SPA', 'reborn'],
    ],
  },
  {
    id: 'ball', cls: Ball, cfg: BALL, pilot: 'ball',
    unit: 'RB-79 BALL', unitShort: 'BALL', unitJp: 'ボール', pilotName: 'BALL LEADER', pilotJp: 'ボール隊長',
    stats: { MELEE: 600, SHOT: 600, DEFENSE: 506, ARMOR: 9087, MOBILITY: 240, THRUSTER: 904 },
    equipment: ['180mm Recoilless Cannon', 'Manipulator Arms'],
    role: 'Pride of mass production. A space pod that tumbles in claws first, shells everything else, and calls in its squadron.',
    moves: [
      ['J ×6', 'Tumbling claw swipes, ending in a launching backflip', 'reborn'],
      ['K', '180mm cannon: mash it, or hold for a heavy shell', 'reborn'],
      ['J K', 'Claw flurry into a rising launcher', 'reborn'],
      ['J J K', 'Tuck in and roll like a bowling ball', 'new'],
      ['J×5 K', 'Meteor drop', 'new'],
      ['SP (hold)', 'Call in the Ball squadron, six volleys a stock', 'new'],
    ],
    guide: [
      ['J J J J J J', 'Claw swipes, somersault, launching flip', 'N', 'reborn'],
      ['K', '180mm cannon · mash, or hold for heavy shell', 'C1', 'reborn'],
      ['J K', 'Claw flurry, rising launcher', 'C2', 'reborn'],
      ['J J K', 'Bowling-ball roll', 'C3', 'new'],
      ['J J J K', 'Spinning top', 'C4', 'new'],
      ['J J J J K', 'Launch and shell it ×3', 'C5', 'new'],
      ['J J J J J K', 'Meteor drop', 'C6', 'new'],
      ['B J', 'Spinning dash · keep pressing J', 'DA', 'reborn'],
      ['B K', 'Spin, then point-blank shell', 'DC', 'reborn'],
      ['U J', 'Air tumble', 'JA', 'new'],
      ['U K', 'Cannon at the ground', 'JC', 'new'],
      ['S', 'Claw frenzy, point-blank shell · hold: squadron', 'SP', ['reborn', 'new']],
      ['U S', 'Ram and blast', 'SPA', 'reborn'],
    ],
  },
  {
    id: 'deltaplus', cls: DeltaPlus, cfg: DELTAPLUS, pilot: 'riddhe',
    unit: 'MSN-001A1 DELTA PLUS', unitShort: 'DELTA PLUS', unitJp: 'デルタプラス', pilotName: 'RIDDHE MARCENAS', pilotJp: 'リディ・マーセナス',
    stats: { MELEE: 600, SHOT: 600, DEFENSE: 480, ARMOR: 10000, MOBILITY: 728, THRUSTER: 1000 },
    equipment: ['Beam Saber', 'Beam Rifle', 'Grenade Launcher', 'Beam Cannon'],
    role: 'Transformable ace machine. Taller and later than the rest of the field; folds into its waverider mode to fly at the line, then a shield-mounted grenade launcher for whatever is still standing.',
    moves: [
      ['J ×4', 'Beam saber string, ending in the shield sabers\' twin X-slash', 'reborn'],
      ['K', 'Beam rifle: mash it (five shots), or hold for a charge shot', 'reborn'],
      ['J J K (K)', 'Shield saber thrust · K if it connects: kick, air cuts, two grenades', 'reborn'],
      ['J J J K', 'Folds into waverider mode and barrel-rolls through', 'reborn'],
      ['B B J', 'Transform Shot: waverider flight, then the beam cannon', 'reborn'],
      ['SP (hold)', 'Waverider vortex, three shots into a huge blast · hold: longer', ['reborn', 'new']],
    ],
    guide: [
      ['J J J J', 'Saber string, shield sabers\' twin X-slash', 'N', 'reborn'],
      ['K', 'Beam rifle · mash, or hold for charge shot', 'C1', 'reborn'],
      ['J K', 'Flip kick, two diagonal slashes in the air', 'C2', 'reborn'],
      ['J J K', 'Shield saber thrust · K if it hits: kick, grenades', 'C3', 'reborn'],
      ['J J J K', 'Transform and barrel-roll through', 'C4', 'reborn'],
      ['J J J J K', 'Rising crescent', 'C5', 'new'],
      ['B J J', 'Bayonet swings, grenade round', 'DA', 'reborn'],
      ['B K', 'Dash cuts, spin, point-blank grenade', 'DC', 'reborn'],
      ['B B J', 'Transform Shot: waverider, beam cannon', 'TS', 'reborn'],
      ['U J', 'Air slash', 'JA', 'new'],
      ['U K', 'Plunging stab', 'JC', 'new'],
      ['S', 'Waverider vortex, three-shot blast · hold: circles longer', 'SP', ['reborn', 'new']],
      ['U S', 'Concentrated rifle beam, then a swipe', 'SPA', 'reborn'],
    ],
  },
  {
    id: 'f91', cls: F91, cfg: F91_SUIT, pilot: 'seabook',
    unit: 'F91 GUNDAM F91', unitShort: 'GUNDAM F91', unitJp: 'ガンダムF91', pilotName: 'SEABOOK ARNO', pilotJp: 'シーブック・アノー',
    stats: { MELEE: 600, SHOT: 600, DEFENSE: 373, ARMOR: 8406, MOBILITY: 528, THRUSTER: 740 },
    equipment: ['Beam Saber', 'Beam Rifle', 'VSBR', 'Beam Launcher'],
    role: 'Formula-project speedster. Paper-thin armor, but a beam saber string, a rifle, a beam launcher and the twin VSBR on its back to match any Gundam.',
    moves: [
      ['J ×6', 'Beam saber string, ending in a rising slash', 'reborn'],
      ['K', 'Beam rifle: mash it, or hold for a twin VSBR shot', 'reborn'],
      ['J J J K', 'Twin sabers spun as wheels, gliding through', 'reborn'],
      ['J×5 K', 'Hovering glide, three VSBR volleys', 'reborn'],
      ['B K', 'Saber flurry, launch, beam launcher fired up', 'reborn'],
      ['SP (hold)', 'VSBR mega-beam, longer per stock held', 'reborn'],
    ],
    guide: [
      ['J J J J J J', 'Saber string, turning cut, rising slash', 'N', 'reborn'],
      ['K', 'Beam rifle · mash, or hold for twin VSBR', 'C1', 'reborn'],
      ['J K', 'Beam shield grind, kick, rifle shot up', 'C2', 'reborn'],
      ['J J K', 'Launcher, VSBR shot up', 'C3', 'reborn'],
      ['J J J K', 'Twin saber wheels, glide through', 'C4', 'reborn'],
      ['J J J J K', 'Lifting stab into the air', 'C5', 'reborn'],
      ['J J J J J K', 'Hovering glide, three VSBR volleys', 'C6', 'reborn'],
      ['B J', 'Dash rush · keep pressing J', 'DA', 'reborn'],
      ['B K', 'Saber flurry, beam launcher fired up', 'DC', 'reborn'],
      ['U J', 'Air slash', 'JA', 'new'],
      ['U K', 'Plunging stab', 'JC', 'new'],
      ['S', 'Long saber sweeps, cross-slash · hold: VSBR mega-beam', 'SP', 'reborn'],
      ['U S', 'Hover in an M.E.P.E. afterimage sphere', 'SPA', 'reborn'],
    ],
  },
  {
    id: 'x1kai', cls: X1Kai, cfg: X1KAI, pilot: 'tobia',
    unit: 'XM-X1 CROSSBONE GUNDAM X1 KAI', unitShort: 'X1 KAI', unitJp: 'クロスボーン・ガンダムX1改', pilotName: 'TOBIA ARRONAX', pilotJp: 'トビア・アロナクス',
    stats: { MELEE: 600, SHOT: 600, DEFENSE: 150, ARMOR: 10000, MOBILITY: 800, THRUSTER: 1000 },
    equipment: ['Beam Saber & Beam Zanber', 'Buster Gun', 'Brand Marker', 'Screw Whip', 'Heat Dagger'],
    role: 'Space-pirate ace. Twin beam blades and a screw whip that hauls enemies into range, but thin armor that cannot take a real beating.',
    moves: [
      ['J ×6', 'Zanber string, ending in a dual-blade launching cross', 'reborn'],
      ['K', 'Buster gun: mash it, or hold for a sustained beam', 'reborn'],
      ['J K', 'Rising launcher into a heat-dagger slam', 'reborn'],
      ['J J K', 'Beam shield ground into the target, then a launch', 'reborn'],
      ['B K', 'Spinning thruster rush into a point-blank blast', 'reborn'],
      ['SP (hold)', 'Dual-blade flurry · hold: screw whip vortex, longer per stock', 'reborn'],
    ],
    guide: [
      ['J J J J J J', 'Zanber string, dual-blade launching cross', 'N', 'reborn'],
      ['K', 'Buster gun · mash, or hold for a sustained beam', 'C1', 'reborn'],
      ['J K', 'Launcher into a heat-dagger slam', 'C2', 'reborn'],
      ['J J K', 'Beam shield grind, launching slash', 'C3', 'reborn'],
      ['J J J K', 'Screw whip: lash and haul in', 'C4', 'reborn'],
      ['J J J J K', 'Launch and chase with a spinning flurry', 'C5', 'reborn'],
      ['J J J J J K', 'Screw whip vortex, dash through', 'C6', 'reborn'],
      ['B J', 'Dash rush · keep pressing J', 'DA', 'reborn'],
      ['B K', 'Spinning thruster rush, point-blank blast', 'DC', 'reborn'],
      ['U J', 'Air zanber cut', 'JA', 'new'],
      ['U K', 'Heat-dagger plunge', 'JC', 'new'],
      ['S', 'Dual-blade flurry and cross-slash · hold: screw whip vortex', 'SP', 'reborn'],
      ['U S', 'Hover in the mantle, a pink orb detonates', 'SPA', 'reborn'],
    ],
  },
  {
    id: 'sazabi', cls: Sazabi, cfg: SAZABI, pilot: 'charcca',
    unit: 'MSN-04 SAZABI', unitShort: 'SAZABI', unitJp: 'サザビー', pilotName: 'CHAR AZNABLE', pilotJp: 'シャア・アズナブル',
    stats: { MELEE: 600, SHOT: 600, DEFENSE: 368, ARMOR: 10000, MOBILITY: 559, THRUSTER: 1000 },
    equipment: ['Beam Tomahawk & Beam Saber', 'Beam Shot Rifle', 'Funnel', 'Missile', 'Mega Particle Cannon'],
    role: "The Red Comet's Neo Zeon flagship. Big and slow, but a beam tomahawk, a heavy shot rifle, six funnels and a mega particle cannon in its belly hit as hard as anything on the field.",
    moves: [
      ['J ×6', 'Beam tomahawk cuts, ending in a rising thruster slash', 'reborn'],
      ['K', 'Beam shot rifle: mash it, or hold to launch and set the funnels on it', 'reborn'],
      ['J K (K)', 'Tomahawk spin, mega particle cannon · K: dash and launch', 'reborn'],
      ['J J K', 'Launch the target and surround it with funnels', 'reborn'],
      ['J×5 K', 'Funnels ring the suit and fire in every direction', 'reborn'],
      ['SP (hold)', 'Tomahawk and funnel frenzy, longer per stock held', 'reborn'],
    ],
    guide: [
      ['J J J J J J', 'Tomahawk cuts, rising thruster slash', 'N', 'reborn'],
      ['K', 'Shot rifle · mash, or hold: launch and funnel volley', 'C1', 'reborn'],
      ['J K', 'Spin, mega particle cannon · K: dash, launch', 'C2', 'reborn'],
      ['J J K', 'Launch, funnels surround and fire', 'C3', 'reborn'],
      ['J J J K', 'Thruster spin sweep', 'C4', 'reborn'],
      ['J J J J K', 'Rising thruster flurry', 'C5', 'reborn'],
      ['J J J J J K', 'Funnels ring the suit, fire all around', 'C6', 'reborn'],
      ['B J', 'Dash cuts · keep pressing J', 'DA', 'reborn'],
      ['B K', 'Dash cuts, uppercut, rifle beam up', 'DC', 'reborn'],
      ['U J', 'Air tomahawk chop', 'JA', 'new'],
      ['U K', 'Missile volley at the ground', 'JC', 'new'],
      ['S', 'Funnel rain, funnel line volley · hold: frenzy', 'SP', 'reborn'],
      ['U S', 'Hover and hammer the ground with the rifle', 'SPA', 'reborn'],
    ],
  },
  {
    id: 'guntank', cls: Tank, pilot: 'hayato', coop: true,
    unit: 'RX-75 GUNTANK', unitShort: 'GUNTANK', unitJp: 'ガンタンク', pilotName: 'HAYATO KOBAYASHI', pilotJp: 'ハヤト・コバヤシ',
    stats: { MELEE: 300, SHOT: 700, DEFENSE: 600, ARMOR: 10000, MOBILITY: 450, THRUSTER: 500 },
    equipment: ['4-tube Missile Launchers', '120mm Cannons'],
    role: 'Co-op support. Missiles that find their own targets and cannon shells lobbed from the back line.',
    moves: [
      ['J', 'Four-missile burst (4th press: eight)'],
      ['K', 'Twin 120mm cannons'],
      ['J J K', 'Six-shell barrage'],
      ['Jump', 'Thruster hop'],
      ['Boost', 'Tread boost'],
      ['SP', 'Full burst: missiles and shells all round'],
    ],
  },
];

// Suits the host can fly (the select screen) and the ones a guest can (everything).
export const SOLO_ROSTER = ROSTER.filter((r) => !r.coop);

export const suitInfo = (id) => ROSTER.find((r) => r.id === id) || ROSTER[0];
